# Impostazioni comuni
timeout_sec: 10
retries: 2
verify_hostname: true
# API paths conformi a ETSI GS QKD 014
api_paths:
  status:    "/api/v1/keys/{slave_id}/status"
  enc_keys:  "/api/v1/keys/{slave_id}/enc_keys"
  dec_keys:  "/api/v1/keys/{master_id}/dec_keys"